<?php

const DIRNAME_TEMPLATECACHE = 'templates';
const DIRNAME_CACHE = 'cache';
const DIRNAME_DOCROOT = 'web';
const DIRNAME_LOGS = 'logs';

define('PATH_BASEDIR', __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR);
define('PATH_DOCROOT', PATH_BASEDIR.DIRNAME_DOCROOT.DIRECTORY_SEPARATOR);
define('PATH_CACHE', PATH_BASEDIR.DIRNAME_CACHE.DIRECTORY_SEPARATOR);
define('PATH_TEMPLATECACHE', PATH_CACHE.DIRNAME_TEMPLATECACHE);
define('PATH_LOGS', PATH_BASEDIR.DIRNAME_LOGS.DIRECTORY_SEPARATOR);
