
maintenancemode: true
debug: false
defaulttimezone: Europe/Berlin
templatecache_enable: false
template_base: base.twig
lang_available:
    de: German
lang_detection_method: legacy
lang_by_domain:
    de: domain.de
admin_page_groups:
    - _|_Keine_
    - admin|Administration
    - verschiedenes|Verschiedenes
    - obsolete|Obsolet
admin_page_types:
    - content
    - contentnosubnav
    - itemoverview
    - itemoverviewgrpd
    - shorturl
locale_format_date: d.m.Y
locale_format_date_time: 'd.m.Y H:i'
defaultcountrybylang:
    de: DE
pagetext_unsafe_html_whitelist: '' # example: 'td[attr],input[attr1|attr2],form'
pagetext_loose_filtering: false
textcat_unsafe_html_whitelist: '' # example: 'td[attr],input[attr1|attr2],form'
textcat_loose_filtering: false
purifier_doctype: 'HTML 4.01 Transitional' # valid values: 'HTML 4.01 Transitional', 'HTML 4.01 Strict', 'XHTML 1.0 Transitional', 'XHTML 1.0 Strict', 'XHTML 1.1'
numberformat_decimals: 2
numberformat_decimal_point: ','
numberformat_thousands_seperator: '.'
allow_parsing_of_page_content: false
email_sendername: 'Sitename Webshop'
email_sender: mail@domain.tld
mail_method: mail # mail (uses the PHP mail() function) / sendmail (uses the systems sendmail) / smtp (use a smtp server, configure server details below)
mail_smtp_server: localhost
mail_smtp_port: 25
mail_smtp_auth: true
mail_smtp_auth_user: username
mail_smtp_auth_pwd: password
mail_smtp_secure: true
mail_smtp_secure_method: tls # tls / ssl
