db_type:        mysql
db_server:      localhost
db_user:        usr
db_password:    pwd
db_name:        dbname

admin_authrealm: HCSF
# If no user is defined here, the whole admin area except adminhome will be disabled.
# Use the encryption tool at the adminhome page to encrypt your password, set blowfish_salt first!
admin_users:
#    adminuser: encryptedadminpwd
